name: Lint

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  push:
    branches:
      - "!main"
      - "!staging"
      - "!pre-release"
      - "!release/*"
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

# Ensure this runs first
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code Style Check
    uses: UncannyOwl/UOCS/.github/workflows/reusable-lint.yml@main
    with:
      standard: automator # or 'api' for API standard
